const data = [
    { englishTerm: "Fight, Evade, Investigate, Movе", revisedCoreSet: "«Атака», «Втеча», «Дослідження», «Переміщення»", previousEditions: "«Атака», «Втеча», «Дослідження», «Переміщення»" },
    { englishTerm: "Arkham Horror: The Card Game", revisedCoreSet: "«Жах Аркгема. Карткова гра»", previousEditions: "«Жах Аркгема. Карткова гра»" },
    { englishTerm: "Act", revisedCoreSet: "Акт", previousEditions: "Справа" },
    { englishTerm: "Asset", revisedCoreSet: "Актив", previousEditions: "здобуток" },
    { englishTerm: "current act", revisedCoreSet: "Активна карта акту", previousEditions: "Поточна загроза" },
    { englishTerm: "Basic weakness", revisedCoreSet: "Базова слабкість", previousEditions: "Базова слабкість" },
    { englishTerm: "Starter Decks", revisedCoreSet: "Базові колоди", previousEditions: "n/a" },
    { englishTerm: "aloof", revisedCoreSet: "Байдужий", previousEditions: "Відчужений" },
    { englishTerm: "Combat", revisedCoreSet: "Бій", previousEditions: "Бій" },
    { englishTerm: "Fight Value", revisedCoreSet: "Бій ворога ", previousEditions: "Сила ворога" },
    { englishTerm: "You get", revisedCoreSet: "Ви отримуєте", previousEditions: "Ви отримуєте" },
    { englishTerm: "choose", revisedCoreSet: "Вибрати", previousEditions: "Вибрати" },
    { englishTerm: "uses", revisedCoreSet: "Використання", previousEditions: "Багаторазовий" },
    { englishTerm: "Heal", revisedCoreSet: "Вилікуйте", previousEditions: "Вилікуйте" },
    { englishTerm: "Remove", revisedCoreSet: "Вилучити", previousEditions: "Прибрати з Гри" },
    { englishTerm: "forced abilities", revisedCoreSet: "Вимушені властивості", previousEditions: "Примусові властивості" },
    { englishTerm: "Exceptional", revisedCoreSet: "Виняткова", previousEditions: "Виняткова" },
    { englishTerm: "exhausted enemy", revisedCoreSet: "Виснажений ворог", previousEditions: "Відчужений ворог" },
    { englishTerm: "Exhausted", revisedCoreSet: "Виснажити / виснажена", previousEditions: "Відчужений" },
    { englishTerm: "Draw 1 card.", revisedCoreSet: "Витягти 1 карту", previousEditions: "Витягти 1 карту" },
    { englishTerm: "delayed effect", revisedCoreSet: "Відкладений ефект", previousEditions: "Відстрочені Ефекти" },
    { englishTerm: "Revealed", revisedCoreSet: "Відкрита локація", previousEditions: "Відкрита локація" },
    { englishTerm: "player window", revisedCoreSet: "Вікно нагоди", previousEditions: "Вікно гравця" },
    { englishTerm: "revelation abilities", revisedCoreSet: "Властивості розкриття", previousEditions: "Властивості розкриття" },
    { englishTerm: "Willpower", revisedCoreSet: "Воля", previousEditions: "Воля" },
    { englishTerm: "ENEMY", revisedCoreSet: "Ворог", previousEditions: "Ворог" },
    { englishTerm: "ready enemies", revisedCoreSet: "Ворог напоготові", previousEditions: "Ворог, який перебуває в бою" },
    { englishTerm: "Engage ", revisedCoreSet: "Вступити у бій", previousEditions: "Вступити у бій" },
    { englishTerm: "Ready", revisedCoreSet: "Готова", previousEditions: "Готова" },
    { englishTerm: "Wild", revisedCoreSet: "Джокер", previousEditions: "n/a" },
    { englishTerm: "while", revisedCoreSet: "Доки", previousEditions: "поки / під час " },
    { englishTerm: "Deckbuilding Options", revisedCoreSet: "Допустимі карти", previousEditions: "Можливі карти" },
    { englishTerm: "ClueTokens", revisedCoreSet: "Жетон зачіпки", previousEditions: "Жетон зачіпки" },
    { englishTerm: "Horror Tokens ", revisedCoreSet: "Жетон потрясіння", previousEditions: "Жетон жаху" },
    { englishTerm: "Doom Tokens", revisedCoreSet: "Жетон приреченості", previousEditions: "Жетон приреченості" },
    { englishTerm: "chaos token", revisedCoreSet: "жетон хаосу", previousEditions: "жетон хаосу" },
    { englishTerm: "In Player Order", revisedCoreSet: "За порядком ходу", previousEditions: "у порядку гравців" },
    { englishTerm: "Task", revisedCoreSet: "Завдання", previousEditions: "n/a" },
    { englishTerm: "deal damage/horror", revisedCoreSet: "Завдати рани / потрясіння", previousEditions: "Нанесення ран / жаху" },
    { englishTerm: "Advancing the Act Deck", revisedCoreSet: "Завершення акту (просування колодою актів)", previousEditions: "Просувати колоду справ" },
    { englishTerm: "advance", revisedCoreSet: "Завершіть акт / зростає загроза", previousEditions: "Просунути колоду справ / загроз" },
    { englishTerm: "Agenda", revisedCoreSet: "Загроза", previousEditions: "Загроза" },
    { englishTerm: "initiated", revisedCoreSet: "Задіяти / задіяна властивість", previousEditions: "n/a" },
    { englishTerm: "Unrevealed Location", revisedCoreSet: "Закрита локація", previousEditions: "Закрита локація" },
    { englishTerm: "committed", revisedCoreSet: "Залучати / залучення", previousEditions: "на перевірку" },
    { englishTerm: "Mulligan", revisedCoreSet: "Заміна початкових карт", previousEditions: "Заміна Карт" },
    { englishTerm: "replacement effect", revisedCoreSet: "Замінний ефект", previousEditions: "Замінний ефект" },
    { englishTerm: "Shuffle ", revisedCoreSet: "Затасувати / перетасувати", previousEditions: "Затасувати / перетасувати" },
    { englishTerm: "clue", revisedCoreSet: "Зачіпка", previousEditions: "здогадка" },
    { englishTerm: "defeat ", revisedCoreSet: "Здолати", previousEditions: "перемогти" },
    { englishTerm: "elder sign", revisedCoreSet: "Знак Прадавніх", previousEditions: "Знак Прадавніх" },
    { englishTerm: "Threat Area", revisedCoreSet: "Зона небезпеки", previousEditions: "Зона Боротьби" },
    { englishTerm: "out-of-play area", revisedCoreSet: "Зона поза грою", previousEditions: "Зона поза грою" },
    { englishTerm: "The Gathering", revisedCoreSet: "Зустріч", previousEditions: "Зібрання" },
    { englishTerm: "game state", revisedCoreSet: "Ігрова ситуація", previousEditions: "Ігрова ситуація" },
    { englishTerm: "game element ", revisedCoreSet: "Ігровий елемент", previousEditions: "Ігровий елемент" },
    { englishTerm: "Intellect", revisedCoreSet: "Інтелект", previousEditions: "Інтелект" },
    { englishTerm: "Act Card", revisedCoreSet: "Карт акту", previousEditions: "Карта справи" },
    { englishTerm: "asset cards ", revisedCoreSet: "Карта активу / карти активів", previousEditions: "Карта здобутку / здобутків" },
    { englishTerm: "higher level cards ", revisedCoreSet: "Карта вищого рівня", previousEditions: "Карта вищого рівня" },
    { englishTerm: "Agenda Card", revisedCoreSet: "Карта загрози", previousEditions: "Карта загроз" },
    { englishTerm: "encounter cards", revisedCoreSet: "Карти контактів", previousEditions: "Карти контактів" },
    { englishTerm: "Treachery Card", revisedCoreSet: "Карти напасті", previousEditions: "Карта підступності" },
    { englishTerm: "keywords", revisedCoreSet: "Ключові слова", previousEditions: "Ключові слова" },
    { englishTerm: "when", revisedCoreSet: "Коли", previousEditions: "Коли" },
    { englishTerm: "agenda deck", revisedCoreSet: "Колода загроз", previousEditions: "Колода загроз" },
    { englishTerm: "control", revisedCoreSet: "Контролювати / під контролем", previousEditions: "Володіти / розпоряджатися" },
    { englishTerm: "pips", revisedCoreSet: "Крапка", previousEditions: "n/a" },
    { englishTerm: "Limits", revisedCoreSet: "Ліміт", previousEditions: "Ліміт" },
    { englishTerm: "LOCATION", revisedCoreSet: "Локація", previousEditions: "Локація" },
    { englishTerm: "Maximum", revisedCoreSet: "Максимум", previousEditions: "Максимум" },
    { englishTerm: "Massive", revisedCoreSet: "Масивний", previousEditions: "Масивний" },
    { englishTerm: "Objective", revisedCoreSet: "Мета", previousEditions: "Ціль" },
    { englishTerm: "Fast", revisedCoreSet: "Миттєва", previousEditions: "Миттєво" },
    { englishTerm: "Slot", revisedCoreSet: "Місця для активів", previousEditions: "Слоти" },
    { englishTerm: "Mythos", revisedCoreSet: "Міф", previousEditions: "Міф" },
    { englishTerm: "shroud value", revisedCoreSet: "Морок локації", previousEditions: "Морок локації" },
    { englishTerm: "Retaliate", revisedCoreSet: "Мстивий", previousEditions: "Месник" },
    { englishTerm: "Surge", revisedCoreSet: "Навала", previousEditions: "Навала" },
    { englishTerm: "Skill", revisedCoreSet: "Навичка", previousEditions: "Вміння" },
    { englishTerm: "Treachery", revisedCoreSet: "Напасть", previousEditions: "Підступність" },
    { englishTerm: "instead", revisedCoreSet: "Натомість / замість", previousEditions: "Натомість / замість" },
    { englishTerm: "Cannot", revisedCoreSet: "Не може", previousEditions: "Не може" },
    { englishTerm: "Deckbuilding Requirements", revisedCoreSet: "Обов'язкові карти", previousEditions: "Обов'язкові карти" },
    { englishTerm: "experience points", revisedCoreSet: "Одиниця досвіду", previousEditions: "Бал досвіду" },
    { englishTerm: "Qualifiers", revisedCoreSet: "Означення", previousEditions: "n/a" },
    { englishTerm: "The Midnight Masks", revisedCoreSet: "Опівнічні маски", previousEditions: "Опівнічні маски" },
    { englishTerm: "moved to…", revisedCoreSet: "Переміститися в", previousEditions: "Переміститися в" },
    { englishTerm: "enter ", revisedCoreSet: "Переміститися в локацію", previousEditions: "Переміститися в локацію" },
    { englishTerm: "Move", revisedCoreSet: "Переміщення", previousEditions: "Переміщення" },
    { englishTerm: "Hunter", revisedCoreSet: "Переслідувач", previousEditions: "Мисливець" },
    { englishTerm: "during", revisedCoreSet: "Під час", previousEditions: "Під час" },
    { englishTerm: "after", revisedCoreSet: "Після", previousEditions: "Після" },
    { englishTerm: "must", revisedCoreSet: "Повинен", previousEditions: "n/a" },
    { englishTerm: "Event", revisedCoreSet: "Подія", previousEditions: "Подія" },
    { englishTerm: "Doom Threshold", revisedCoreSet: "Поріг приреченості", previousEditions: "Число Приреченості" },
    { englishTerm: "empty location", revisedCoreSet: "Порожня локація", previousEditions: "Порожня локація" },
    { englishTerm: "constant", revisedCoreSet: "Постійний", previousEditions: "Постійний" },
    { englishTerm: "constant abilities", revisedCoreSet: "Постійні властивості", previousEditions: "Постійні властивості" },
    { englishTerm: "current location", revisedCoreSet: "Поточна локація (але в картах пишемо \"ваша локація\")", previousEditions: "Поточна локація " },
    { englishTerm: "horror", revisedCoreSet: "Потрясіння", previousEditions: "Жах" },
    { englishTerm: "starting resources", revisedCoreSet: "початкові ресурси", previousEditions: "стартові ресурси" },
    { englishTerm: "attachments ", revisedCoreSet: "Приєднана (карта)", previousEditions: "Приєднана (карта)" },
    { englishTerm: "lead investigator", revisedCoreSet: "Провідний дослідник", previousEditions: "Провідний дослідник" },
    { englishTerm: "Direct Damage, Direct Horror", revisedCoreSet: "Прямі рани / потрясіння", previousEditions: "Спрямовані Рани, Спрямований Жах" },
    { englishTerm: "damage", revisedCoreSet: "Рана", previousEditions: "Рана" },
    { englishTerm: "Standalone Mode", revisedCoreSet: "Режим самостійного сценарію", previousEditions: "Одиночний Режим" },
    { englishTerm: "pool", revisedCoreSet: "Резерв", previousEditions: "сховище" },
    { englishTerm: "resource", revisedCoreSet: "Ресурс", previousEditions: "Ресурс" },
    { englishTerm: "Traits", revisedCoreSet: "Риси", previousEditions: "Риси" },
    { englishTerm: "Level of difficulty: Easy  Standard Hard Expert", revisedCoreSet: "Рівень складності: Простий Нормальний Складний Експертний", previousEditions: "Рівень складності: Легкий Середній Важкий Надважкий\"" },
    { englishTerm: "resolution ", revisedCoreSet: "Розв'язка", previousEditions: "Розв'язка" },
    { englishTerm: "Play", revisedCoreSet: "Розіграти", previousEditions: "Зіграти" },
    { englishTerm: "Play only during your turn", revisedCoreSet: "Розігруйте лише у свій хід", previousEditions: "n/a" },
    { englishTerm: "Revelation", revisedCoreSet: "Розкриття", previousEditions: "Розкриття" },
    { englishTerm: "Deck Size", revisedCoreSet: "Розмір колоди", previousEditions: "Розмір колоди" },
    { englishTerm: "Sanity", revisedCoreSet: "Розсудок", previousEditions: "Розум" },
    { englishTerm: "standalone scenario", revisedCoreSet: "Самостійний сценарій", previousEditions: "окремо взятий сценарій" },
    { englishTerm: "encounter set icon", revisedCoreSet: "Символ набору контактів", previousEditions: "Символ набору контактів" },
    { englishTerm: "Connection Symbols", revisedCoreSet: "Символи зв’язків", previousEditions: "Символи Сполучення" },
    { englishTerm: "Cancel", revisedCoreSet: "Скасувати", previousEditions: "Відмінити" },
    { englishTerm: "group limit", revisedCoreSet: "Спільний ліміт", previousEditions: "Спільний ліміт" },
    { englishTerm: "as a group", revisedCoreSet: "Спільно", previousEditions: "Спільно" },
    { englishTerm: "resolved", revisedCoreSet: "Спрацювати / застосувати", previousEditions: "n/a" },
    { englishTerm: "Agility", revisedCoreSet: "Спритність", previousEditions: "Спритність" },
    { englishTerm: "attack of opportunity", revisedCoreSet: "Спровокована атака", previousEditions: "Атака на Випередження" },
    { englishTerm: "framework event", revisedCoreSet: "Структурна подія", previousEditions: "Структурна подія" },
    { englishTerm: "framework effect", revisedCoreSet: "Структурний ефект", previousEditions: "Структурний ефект" },
    { englishTerm: "entity", revisedCoreSet: "Суб'єкт / об'єкт", previousEditions: "об'єкт" },
    { englishTerm: "connecting location", revisedCoreSet: "Суміжна локація", previousEditions: "Сполучена локація" },
    { englishTerm: "Story Assets", revisedCoreSet: "Сюжетні активи", previousEditions: "Сюжетні Здобутки" },
    { englishTerm: "only", revisedCoreSet: "Тільки", previousEditions: "Тільки" },
    { englishTerm: "Then", revisedCoreSet: "Тоді", previousEditions: "Після" },
    { englishTerm: "chaos bag", revisedCoreSet: "Торба хаосу", previousEditions: "Вмістилище хаосу" },
    { englishTerm: "trauma", revisedCoreSet: "Травма", previousEditions: "Травма" },
    { englishTerm: "lasting effect", revisedCoreSet: "Тривалий ефект", previousEditions: "Тривалий ефект" },
    { englishTerm: "If you succeed", revisedCoreSet: "У разі успіху / у разі успішної перевірки", previousEditions: "У разі успіху / у разі успішної перевірки" },
    { englishTerm: "discard ", revisedCoreSet: "У скид", previousEditions: "відбій (карти скидаються)" },
    { englishTerm: "Peril", revisedCoreSet: "Халепа", previousEditions: "Небезпека" },
    { englishTerm: "if", revisedCoreSet: "Якщо", previousEditions: "Якщо" },
    { englishTerm: "Uptown", revisedCoreSet: "Аптаун", previousEditions: "Аптаун" },
    { englishTerm: "Arkham", revisedCoreSet: "Аркгем", previousEditions: "Аркгем" },
    { englishTerm: "Arkham Woods", revisedCoreSet: "Аркгемські ліси", previousEditions: "Аркгемські ліси" },
    { englishTerm: "Orne Library", revisedCoreSet: "Бібліотека Орна", previousEditions: "Бібліотека Орна" },
    { englishTerm: "Downtown", revisedCoreSet: "Даунтаун", previousEditions: "Даунтаун" },
    { englishTerm: "Historical Society", revisedCoreSet: "Історичне товариство", previousEditions: "Історичне товариство" },
    { englishTerm: "Easttown", revisedCoreSet: "Істтаун", previousEditions: "Істтаун" },
    { englishTerm: "St. Mary’s Hospital", revisedCoreSet: "Лікарня святої Марії", previousEditions: "Лікарня святої Марії" },
    { englishTerm: "Miskatonic University", revisedCoreSet: "Міскатонікський університет", previousEditions: "Міскатонікський університет" },
    { englishTerm: "City Hall", revisedCoreSet: "Міська мерія", previousEditions: "Міська мерія" },
    { englishTerm: "Northside", revisedCoreSet: "Нортсайд", previousEditions: "Нортсайд" },
    { englishTerm: "Ma’s Boarding House", revisedCoreSet: "Пансіон Ма", previousEditions: "Пансіонат / Пансіон Матінки" },
    { englishTerm: "The First Bank of Arkham", revisedCoreSet: "Перший банк Аркгема", previousEditions: "Перший банк Аркгема" },
    { englishTerm: "South Church", revisedCoreSet: "Південна церква", previousEditions: "Південна церква" },
    { englishTerm: "Independence Square", revisedCoreSet: "Площа Незалежності", previousEditions: "Площа Незалежності" },
    { englishTerm: "Arkham Police Station", revisedCoreSet: "Поліційний відділок Аркгема", previousEditions: "Поліційний відділок Аркгема" },
    { englishTerm: "Arkham Asylum", revisedCoreSet: "Психіатрична клініка", previousEditions: "Аркгемська Клініка" },
    { englishTerm: "R’lyeh", revisedCoreSet: "Р’льєх", previousEditions: "Р’льєх" },
    { englishTerm: "Velma’s Diner", revisedCoreSet: "Ресторанчик Вельми", previousEditions: "Ресторанчик Вельми" },
    { englishTerm: "Rivertown", revisedCoreSet: "Рівертаун", previousEditions: "Рівертаун" },
    { englishTerm: "Miskatonic River", revisedCoreSet: "Річка Міскатонік", previousEditions: "Річка Міскатонік" },
    { englishTerm: "Southside", revisedCoreSet: "Саутсайд", previousEditions: "Саузсайд " },
    { englishTerm: "Mystery Meat Mondays", revisedCoreSet: "Таємниче м’ясо щопонеділка", previousEditions: "Понеділки Загадкового М’яса" },
    { englishTerm: "French Hill", revisedCoreSet: "Френчхіл", previousEditions: "Французський пагорб" },
    { englishTerm: "“Wolf-Man” Drew", revisedCoreSet: "«Людина-вовк» Дрю", previousEditions: "«Людина-вовк» Дрю" },
    { englishTerm: "Acolyte", revisedCoreSet: "Аколіт", previousEditions: "Прислужник" },
    { englishTerm: "Ancient One", revisedCoreSet: "Прадавній", previousEditions: "Прадавній" },
    { englishTerm: "Byakhee", revisedCoreSet: "Б’якгі", previousEditions: "Б’якхі" },
    { englishTerm: "Cthulhu", revisedCoreSet: "Ктулху", previousEditions: "Ктулху" },
    { englishTerm: "Dark Young", revisedCoreSet: "Темний нащадок", previousEditions: "Темна Памолодь" },
    { englishTerm: "Deep One", revisedCoreSet: "Глибоководний", previousEditions: "Глибоководний" },
    { englishTerm: "Flesh-Eater", revisedCoreSet: "Пожирач плоті", previousEditions: "Пожирач плоті" },
    { englishTerm: "Ghoul", revisedCoreSet: "Гуль", previousEditions: "Гуль" },
    { englishTerm: "Ghoul Minion", revisedCoreSet: "Гуль-прислужник", previousEditions: "Гуль-прислужник" },
    { englishTerm: "Ghoul Priest", revisedCoreSet: "Гуль-жрець", previousEditions: "Гуль-жрець" },
    { englishTerm: "Goat Spawn", revisedCoreSet: "Козяче поріддя", previousEditions: "Козлине Поріддя" },
    { englishTerm: "Hunting Nightgaunt", revisedCoreSet: "Нічвида-мисливець", previousEditions: "Нічна Примара, яка Полює" },
    { englishTerm: "Icy Ghoul", revisedCoreSet: "Льодяний гуль", previousEditions: "Крижаний Гуль" },
    { englishTerm: "Mob Enforcer", revisedCoreSet: "Гангстер", previousEditions: "Збирач Боргів" },
    { englishTerm: "Ravenous Ghoul", revisedCoreSet: "Ненажерливий гуль", previousEditions: "Зголоднілий Гуль" },
    { englishTerm: "Relentless Dark Young", revisedCoreSet: "Лютий темний нащадок", previousEditions: "Безжалісна Темна Памолодь" },
    { englishTerm: "Screeching Byakhee", revisedCoreSet: "Вересклива б’якгі", previousEditions: "Верескливий Б’якхі" },
    { englishTerm: "Silver Twilight Acolyte", revisedCoreSet: "Аколіт Срібних сутінок", previousEditions: "Прислужник Срібних Сутінків" },
    { englishTerm: "Stubborn Detective", revisedCoreSet: "Надокучливий детектив", previousEditions: "Впертий Детектив" },
    { englishTerm: "The Devourer Below", revisedCoreSet: "Пожирач із глибин", previousEditions: "Пожирач із глибин" },
    { englishTerm: "The Masked Hunter", revisedCoreSet: "Переслідувач у масці", previousEditions: "Мисливець у масці" },
    { englishTerm: "Umôrdhoth", revisedCoreSet: "Умордхот", previousEditions: "Умордхот" },
    { englishTerm: "Wizard of the Order", revisedCoreSet: "Чарівник ордену", previousEditions: "Чаклун Ордену" },
    { englishTerm: "Yithian Observer", revisedCoreSet: "Йітіанський спостерігач", previousEditions: "Йітіанський спостерігач" },
    { englishTerm: "Young Deep One", revisedCoreSet: "Молодий глибоководний", previousEditions: "Молодий глибоководний" },
    { englishTerm: "Roland’s .38 Special", revisedCoreSet: "Улюбленець Роланда 38-го калібру", previousEditions: "Улюбленець Роланда 38-го калібру" },
    { englishTerm: "Cover Up", revisedCoreSet: "Знищити докази", previousEditions: "Замісти Сліди" },
    { englishTerm: "Daisy’s Tote Bag", revisedCoreSet: "Торбинка Дейзі", previousEditions: "Торбинка Дейзі" },
    { englishTerm: "The Necronomicon", revisedCoreSet: "Некрономікон", previousEditions: "Некрономікон" },
    { englishTerm: "On the Lam", revisedCoreSet: "На втіках", previousEditions: "На втіках" },
    { englishTerm: "Hospital Debts", revisedCoreSet: "Борг за лікування", previousEditions: "Лікарняні Борги" },
    { englishTerm: "Heirloom of Hyperborea", revisedCoreSet: "Гіперборейська реліквія", previousEditions: "Гіперборейська реліквія" },
    { englishTerm: "Dark Memory", revisedCoreSet: "Темні спогади", previousEditions: "Темні спогади" },
    { englishTerm: "Wendy’s Amulet", revisedCoreSet: "Амулет Венді", previousEditions: "Амулет Венді" },
    { englishTerm: "Abandoned and Alone", revisedCoreSet: "Самотня і покинута", previousEditions: "Покинутість і Самотність" },
    { englishTerm: ".45 Automatic", revisedCoreSet: "Кольт 45-го калібру", previousEditions: "Кольт 45-го калібру" },
    { englishTerm: "Physical Training", revisedCoreSet: "Фізична підготовка", previousEditions: "Фізична підготовка" },
    { englishTerm: "Beat Cop", revisedCoreSet: "Патрульний", previousEditions: "Патрульний" },
    { englishTerm: "First Aid", revisedCoreSet: "Аптечка", previousEditions: "Перша Допомога" },
    { englishTerm: "Machete", revisedCoreSet: "Мачете", previousEditions: "Мачете" },
    { englishTerm: "Guard Dog", revisedCoreSet: "Сторожовий пес", previousEditions: "Сторожовий пес" },
    { englishTerm: "Evidence!", revisedCoreSet: "Доказ!", previousEditions: "Доказ!" },
    { englishTerm: "Dodge", revisedCoreSet: "Ухилення", previousEditions: "Ухилення" },
    { englishTerm: "Dynamite Blast", revisedCoreSet: "Вибух динаміту", previousEditions: "Вибух динаміту" },
    { englishTerm: "Vicious Blow", revisedCoreSet: "Лютий удар", previousEditions: "Нищівний Удар" },
    { englishTerm: "Extra Ammunition", revisedCoreSet: "Запасні набої", previousEditions: "Додаткові Боєприпаси" },
    { englishTerm: "Police Badge", revisedCoreSet: "Поліцейський значок", previousEditions: "Поліційний Жетон" },
    { englishTerm: "Beat Cop", revisedCoreSet: "Патрульний", previousEditions: "Патрульний" },
    { englishTerm: "Shotgun", revisedCoreSet: "Дробовик", previousEditions: "Дробовик" },
    { englishTerm: "Magnifying Glass", revisedCoreSet: "Лупа", previousEditions: "Лупа" },
    { englishTerm: "Old Book of Lore", revisedCoreSet: "Стародавній фоліант", previousEditions: "Стара Книга Знань" },
    { englishTerm: "Research Librarian", revisedCoreSet: "Бібліотекар", previousEditions: "Бібліотекар-Консультант" },
    { englishTerm: "Dr. Milan Christopher", revisedCoreSet: "Доктор Мілан Крістофер", previousEditions: "Доктор Мілан Крістофер" },
    { englishTerm: "Hyperawareness", revisedCoreSet: "Надчутливість", previousEditions: "Надчутливість" },
    { englishTerm: "Medical Texts", revisedCoreSet: "Медична енциклопедія", previousEditions: "Медичні Записи" },
    { englishTerm: "Mind over Matter", revisedCoreSet: "Розум над матерією", previousEditions: "Дух Сильніше Плоті" },
    { englishTerm: "Working a Hunch", revisedCoreSet: "Інтуїція слідчого", previousEditions: "Слідуючи за Підказками" },
    { englishTerm: "Barricade", revisedCoreSet: "Барикада", previousEditions: "Барикада" },
    { englishTerm: "Deduction", revisedCoreSet: "Дедукція", previousEditions: "Дедукція" },
    { englishTerm: "Magnifying Glass", revisedCoreSet: "Лупа", previousEditions: "Лупа" },
    { englishTerm: "Disc of Itzamna", revisedCoreSet: "Диск Ітзамни", previousEditions: "Диск Іцамни" },
    { englishTerm: "Encyclopedia", revisedCoreSet: "Енциклопедія", previousEditions: "Енциклопедія" },
    { englishTerm: "Cryptic Research", revisedCoreSet: "Загадкове дослідження", previousEditions: "Таємні Дослідження" },
    { englishTerm: "Switchblade", revisedCoreSet: "Викидний ніж", previousEditions: "Викидний ніж" },
    { englishTerm: "Burglary", revisedCoreSet: "Мародерство", previousEditions: "Пограбування" },
    { englishTerm: "Pickpocketing", revisedCoreSet: "Крадіжка", previousEditions: "Кишенькова Крадіжка" },
    { englishTerm: ".41 Derringer", revisedCoreSet: "Деррінджер 41-го калібру", previousEditions: "Деррінджер 41-го калібру" },
    { englishTerm: "Leo De Luca", revisedCoreSet: "Лео де Лука", previousEditions: "Лео де Лука" },
    { englishTerm: "Hard Knocks", revisedCoreSet: "Дитя нетрів", previousEditions: "Загартованість Життям" },
    { englishTerm: "Elusive", revisedCoreSet: "Невловимість", previousEditions: "Невловимість" },
    { englishTerm: "Backstab", revisedCoreSet: "Удар у спину", previousEditions: "Удар у спину" },
    { englishTerm: "Sneak Attack", revisedCoreSet: "Підступний напад", previousEditions: "Напад Зненацька" },
    { englishTerm: "Opportunist", revisedCoreSet: "Пристосуванець", previousEditions: "Кмітливість" },
    { englishTerm: "Leo De Luca", revisedCoreSet: "Лео де Лука", previousEditions: "Лео де Лука" },
    { englishTerm: "Cat Burglar", revisedCoreSet: "Злодій-домушник", previousEditions: "Зломщик" },
    { englishTerm: "Sure Gamble", revisedCoreSet: "Прорахований ризик", previousEditions: "Впевнена Гра" },
    { englishTerm: "Hot Streak", revisedCoreSet: "Біла смуга", previousEditions: "Біла смуга" },
    { englishTerm: "Forbidden Knowledge", revisedCoreSet: "Заборонені знання", previousEditions: "Заборонені знання" },
    { englishTerm: "Holy Rosary", revisedCoreSet: "Свята вервиця", previousEditions: "Свята вервиця" },
    { englishTerm: "Shrivelling", revisedCoreSet: "В’янення", previousEditions: "Висушування" },
    { englishTerm: "Scrying", revisedCoreSet: "Ворожіння", previousEditions: "Ворожіння" },
    { englishTerm: "Arcane Studies", revisedCoreSet: "Вивчення магії", previousEditions: "Вивчення магії" },
    { englishTerm: "Arcane Initiate", revisedCoreSet: "Учениця чаклуна", previousEditions: "Посвячена" },
    { englishTerm: "Drawn to the Flame", revisedCoreSet: "Тяга до незвіданого", previousEditions: "Летіти На Вогонь" },
    { englishTerm: "Ward of Protection", revisedCoreSet: "Захисне коло", previousEditions: "Захисна Магія" },
    { englishTerm: "Blinding Light", revisedCoreSet: "Засліплення", previousEditions: "Осліпляюче Світло" },
    { englishTerm: "Fearless", revisedCoreSet: "Безстрашність", previousEditions: "Безстрашність" },
    { englishTerm: "Mind Wipe", revisedCoreSet: "Стерти пам’ять", previousEditions: "Стирання Розуму" },
    { englishTerm: "Blinding Light", revisedCoreSet: "Засліплення", previousEditions: "Осліпляюче Світло" },
    { englishTerm: "Book of Shadows", revisedCoreSet: "Книга тіней", previousEditions: "Книга тіней" },
    { englishTerm: "Grotesque Statue", revisedCoreSet: "Потворна статуя", previousEditions: "Химерна Статуетка" },
    { englishTerm: "Leather Coat", revisedCoreSet: "Шкіряне пальто", previousEditions: "Шкіряне пальто" },
    { englishTerm: "Scavenging", revisedCoreSet: "Бери що знайдеш", previousEditions: "Копирсання у Смітті" },
    { englishTerm: "Baseball Bat", revisedCoreSet: "Бейсбольна бита", previousEditions: "Бейсбольна бита" },
    { englishTerm: "Rabbit’s Foot", revisedCoreSet: "Кроляча лапка", previousEditions: "Кроляча лапка" },
    { englishTerm: "Stray Cat", revisedCoreSet: "Безпритульний кіт", previousEditions: "Бродячий Кіт" },
    { englishTerm: "Dig Deep", revisedCoreSet: "Довести до кінця", previousEditions: "Завзятість" },
    { englishTerm: "Cunning Distraction", revisedCoreSet: "Відвернення уваги", previousEditions: "Відвернення уваги" },
    { englishTerm: "“Look what I found!”", revisedCoreSet: "«Диви, що я знайшов!»", previousEditions: "«Дивіться, що я знайшов!»" },
    { englishTerm: "Lucky!", revisedCoreSet: "Пощастило!", previousEditions: "Пощастило!" },
    { englishTerm: "Survival Instinct", revisedCoreSet: "Інстинкт виживання", previousEditions: "Інстинкт виживання" },
    { englishTerm: "Close Call", revisedCoreSet: "За крок від смерті", previousEditions: "За крок від смерті" },
    { englishTerm: "Lucky!", revisedCoreSet: "Пощастило!", previousEditions: "Пощастило!" },
    { englishTerm: "Will to Survive", revisedCoreSet: "Воля до життя", previousEditions: "Воля до життя" },
    { englishTerm: "Knife", revisedCoreSet: "Ніж", previousEditions: "Ніж" },
    { englishTerm: "Flashlight", revisedCoreSet: "Ліхтарик", previousEditions: "Ліхтарик" },
    { englishTerm: "Emergency Cache", revisedCoreSet: "Непорушний запас", previousEditions: "Недоторканий Запас" },
    { englishTerm: "Guts", revisedCoreSet: "Хоробрість", previousEditions: "Хоробрість" },
    { englishTerm: "Perception", revisedCoreSet: "Уважність", previousEditions: "Усвідомлення / Проникливість" },
    { englishTerm: "Overpower", revisedCoreSet: "Пересилення", previousEditions: "Пересилення" },
    { englishTerm: "Manual Dexterity", revisedCoreSet: "Вправність рук", previousEditions: "Вправність рук" },
    { englishTerm: "Unexpected Courage", revisedCoreSet: "Відчайдушність", previousEditions: "Неочікувана Сміливість" },
    { englishTerm: "Bulletproof Vest", revisedCoreSet: "Бронежилет", previousEditions: "Куленепробивний Жилет" },
    { englishTerm: "Elder Sign Amulet", revisedCoreSet: "Амулет зі знаком Прадавніх", previousEditions: "Амулет зі знаком Прадавніх" },
    { englishTerm: "Amnesia", revisedCoreSet: "Амнезія", previousEditions: "Амнезія" },
    { englishTerm: "Paranoia", revisedCoreSet: "Параноя", previousEditions: "Параноя" },
    { englishTerm: "Haunted", revisedCoreSet: "Одержимість", previousEditions: "Примари" },
    { englishTerm: "Psychosis", revisedCoreSet: "Психоз", previousEditions: "Психоз" },
    { englishTerm: "Hypochondria", revisedCoreSet: "Іпохондрія", previousEditions: "Іпохондрія" },
    { englishTerm: "Mob Enforcer", revisedCoreSet: "Гангстер", previousEditions: "Збирач Боргів" },
    { englishTerm: "Silver Twilight Acolyte", revisedCoreSet: "Аколіт Срібних сутінок", previousEditions: "Прислужник Срібних Сутінків" },
    { englishTerm: "Stubborn Detective", revisedCoreSet: "Надокучливий детектив", previousEditions: "Впертий Детектив" },
    { englishTerm: "Study", revisedCoreSet: "Кабінет", previousEditions: "Кабінет" },
    { englishTerm: "Hallway", revisedCoreSet: "Коридор", previousEditions: "Передпокій" },
    { englishTerm: "Attic", revisedCoreSet: "Горище", previousEditions: "Горище" },
    { englishTerm: "Cellar", revisedCoreSet: "Підвал", previousEditions: "Підвал" },
    { englishTerm: "Parlor", revisedCoreSet: "Вітальня", previousEditions: "Вітальня" },
    { englishTerm: "Ghoul Priest", revisedCoreSet: "Гуль-жрець", previousEditions: "Гуль-жрець" },
    { englishTerm: "Lita Chantler", revisedCoreSet: "Літа Чантлер", previousEditions: "Літа Чентлер" },
    { englishTerm: "Flesh-Eater", revisedCoreSet: "Пожирач Плоті", previousEditions: "Пожирач Плоті" },
    { englishTerm: "Icy Ghoul", revisedCoreSet: "Льодяний гуль", previousEditions: "Крижаний Гуль" },
    { englishTerm: "Your House", revisedCoreSet: "Ваш дім", previousEditions: "Ваш дім" },
    { englishTerm: "Rivertown", revisedCoreSet: "Рівертаун", previousEditions: "Рівертаун" },
    { englishTerm: "Southside (Historical Society)", revisedCoreSet: "Саутсай (Історичне товариство)", previousEditions: "Саузсайд (Історичне Товариство)" },
    { englishTerm: "Southside (Ma’s Boarding House)", revisedCoreSet: "Саутсайд (Пансіон Ма)", previousEditions: "Саузсайд (Пансіонат Матінки)" },
    { englishTerm: "St. Mary’s Hospital", revisedCoreSet: "Лікарня святої Марії", previousEditions: "Лікарня Св. Марії" },
    { englishTerm: "Miskatonic University", revisedCoreSet: "Міскатонікський університет", previousEditions: "Міскатонікський університет" },
    { englishTerm: "Downtown (First Bank of Arkham)", revisedCoreSet: "Даунтаун (Перший банк Аркгема)", previousEditions: "Даунтаун (Перший банк Аркгема)" },
    { englishTerm: "Downtown (Arkham Asylum)", revisedCoreSet: "Даунтаун (Психіатрична клініка)", previousEditions: "Даунтау (Аркгемська Клініка)" },
    { englishTerm: "Easttown", revisedCoreSet: "Істтаун", previousEditions: "Істтаун" },
    { englishTerm: "Graveyard", revisedCoreSet: "Цвинтар", previousEditions: "Цвинтар" },
    { englishTerm: "Northside", revisedCoreSet: "Нортсайд", previousEditions: "Норзсайд" },
    { englishTerm: "Hunting Shadow", revisedCoreSet: "Тінь-переслідувач", previousEditions: "Тінь, що Переслідує" },
    { englishTerm: "False Lead", revisedCoreSet: "Глухий кут", previousEditions: "Хибний Слід" },
    { englishTerm: "“Wolf-Man” Drew", revisedCoreSet: "«Людина-вовк» Дрю", previousEditions: "«Людина-вовк» Дрю" },
    { englishTerm: "Herman Collins", revisedCoreSet: "Герман Коллінс", previousEditions: "Герман Коллінз" },
    { englishTerm: "Peter Warren", revisedCoreSet: "Пітер Воррен", previousEditions: "Пітер Уоррен" },
    { englishTerm: "Victoria Devereux", revisedCoreSet: "Вікторія Деверо", previousEditions: "Вікторія Деверо" },
    { englishTerm: "Ruth Turner", revisedCoreSet: "Рут Тернер", previousEditions: "Рут Тернер" },
    { englishTerm: "Main Path", revisedCoreSet: "Головна дорога", previousEditions: "Головна Стежка" },
    { englishTerm: "Arkham Woods (Unhallowed Ground)", revisedCoreSet: "Аркгемські ліси (Осквернена земля)", previousEditions: "Аркгемські ліси (Неосвячена Земля)" },
    { englishTerm: "Arkham Woods (Twisting Paths)", revisedCoreSet: "Аркгемські ліси (Заплутана стежка)", previousEditions: "Аркгемські ліси (Звивисті Стежки)" },
    { englishTerm: "Arkham Woods (Old House)", revisedCoreSet: "Аркгемські ліси (Старий будинок)", previousEditions: "Аркгемські ліси (Старий будинок)" },
    { englishTerm: "Arkham Woods (Cliffside)", revisedCoreSet: "Аркгемські ліси (Скеля)", previousEditions: "Аркгемські ліси (Скеля)" },
    { englishTerm: "Arkham Woods (Tangled Thicket)", revisedCoreSet: "Аркгемські ліси (Непрохідні хащі)", previousEditions: "Аркгемські ліси (Непрохідні хащі)" },
    { englishTerm: "Arkham Woods (Quiet Glade)", revisedCoreSet: "Аркгемські ліси (Тиха галявина)", previousEditions: "Аркгемські ліси (Затишна Галявина)" },
    { englishTerm: "Ritual Site", revisedCoreSet: "Місце проведення ритуалу", previousEditions: "Місце Ритуалу" },
    { englishTerm: "Umôrdhoth", revisedCoreSet: "Умордхот", previousEditions: "Умордхот" },
    { englishTerm: "Umôrdhoth’s Wrath", revisedCoreSet: "Гнів Умордхота", previousEditions: "Гнів Умордхота" },
    { englishTerm: "Swarm of Rats", revisedCoreSet: "Зграя щурів", previousEditions: "Зграя щурів" },
    { englishTerm: "Ghoul Minion", revisedCoreSet: "Гуль-прислужник", previousEditions: "Гуль Прислужник" },
    { englishTerm: "Ravenous Ghoul", revisedCoreSet: "Ненажерливий гуль", previousEditions: "Зголоднілий Гуль" },
    { englishTerm: "Grasping Hands", revisedCoreSet: "Чіпкі руки", previousEditions: "Чіпкі руки" },
    { englishTerm: "Rotting Remains", revisedCoreSet: "Гнилі рештки", previousEditions: "Гниючі Рештки" },
    { englishTerm: "Frozen in Fear", revisedCoreSet: "Закляк від жаху", previousEditions: "Завмерти Від Страху" },
    { englishTerm: "Dissonant Voices", revisedCoreSet: "Голоси в голові", previousEditions: "Невгамовні Голоси" },
    { englishTerm: "Ancient Evils", revisedCoreSet: "Прадавнє зло", previousEditions: "Прадавнє зло" },
    { englishTerm: "Crypt Chill", revisedCoreSet: "Могильний холод", previousEditions: "Вбивчий Холод" },
    { englishTerm: "Obscuring Fog", revisedCoreSet: "Непроглядний туман", previousEditions: "Щільний Туман" },
    { englishTerm: "Acolyte", revisedCoreSet: "Аколіт", previousEditions: "Прислужник" },
    { englishTerm: "Wizard of the Order", revisedCoreSet: "Чарівник ордену", previousEditions: "Чаклун Ордену" },
    { englishTerm: "Mysterious Chanting", revisedCoreSet: "Загадковий наспів", previousEditions: "Таємниче Наспівування" },
    { englishTerm: "Hunting Nightgaunt", revisedCoreSet: "Нічвида-мисливець", previousEditions: "Нічна Примара, яка Полює" },
    { englishTerm: "On Wings of Darkness", revisedCoreSet: "На крилах пітьми", previousEditions: "На Крилах Темряви" },
    { englishTerm: "Locked Door", revisedCoreSet: "Замкнені двері", previousEditions: "Замкнені Двері" },
    { englishTerm: "Screeching Byakhee", revisedCoreSet: "Вересклива б’якгі", previousEditions: "Верескливий Б’якхі" },
    { englishTerm: "The Yellow Sign", revisedCoreSet: "Жовтий знак", previousEditions: "Жовтий знак" },
    { englishTerm: "Yithian Observer", revisedCoreSet: "Йітіанський спостерігач", previousEditions: "Йітіанський спостерігач" },
    { englishTerm: "Offer of Power", revisedCoreSet: "Пропозиція сили", previousEditions: "Пропозиція сили" },
    { englishTerm: "Relentless Dark Young", revisedCoreSet: "Лютий темний нащадок", previousEditions: "Безжалісна Темна Памолодь" },
    { englishTerm: "Goat Spawn", revisedCoreSet: "Козяче поріддя", previousEditions: "Козлине Поріддя" },
    { englishTerm: "Young Deep One", revisedCoreSet: "Молодий глибоководний", previousEditions: "Молодий глибоководний" },
    { englishTerm: "Dreams of R’lyeh", revisedCoreSet: "Сни про Р’льєх", previousEditions: "Сни про Р’льєх" },
    { englishTerm: "First Aid", revisedCoreSet: "Аптечка", previousEditions: "n/a" },
    { englishTerm: "“I’ve had worse…”", revisedCoreSet: "«Бувало й гірше...»", previousEditions: "n/a" },
    { englishTerm: "Seeking Answers", revisedCoreSet: "У пошуках відповідей", previousEditions: "n/a" },
    { englishTerm: "Old Book of Lore", revisedCoreSet: "Стародавній фоліант", previousEditions: "n/a" },
    { englishTerm: "Lockpicks", revisedCoreSet: "Відмички", previousEditions: "n/a" },
    { englishTerm: ".41 Derringer", revisedCoreSet: "Деррінджер 41-го калібру", previousEditions: "n/a" },
    { englishTerm: "Rite of Seeking", revisedCoreSet: "Обряд пошуку", previousEditions: "n/a" },
    { englishTerm: "Scrying", revisedCoreSet: "Ворожіння", previousEditions: "n/a" },
    { englishTerm: "Aquinnah", revisedCoreSet: "Аквінна", previousEditions: "n/a" },
    { englishTerm: "Eucatastrophe", revisedCoreSet: "Евкатастрофа", previousEditions: "n/a" },
    { englishTerm: "Emergency Cache", revisedCoreSet: "Непорушний запас", previousEditions: "n/a" },
    { englishTerm: "Charisma", revisedCoreSet: "Харизма", previousEditions: "n/a" },
    { englishTerm: "Relic Hunter", revisedCoreSet: "Мисливець за реліквіями", previousEditions: "n/a" },
    { englishTerm: "«Skids» O’Toole", revisedCoreSet: "«Слизький» О’Тул", previousEditions: "«Слизький» О’Тул" },
    { englishTerm: "Agnes Baker", revisedCoreSet: "Аґнес Бейкер", previousEditions: "Агнес Бейкер" },
    { englishTerm: "Wendy Adams", revisedCoreSet: "Венді Адамс", previousEditions: "Венді Адамс" },
    { englishTerm: "Victoria Devereux", revisedCoreSet: "Вікторія Деверо", previousEditions: "Вікторія Деверо" },
    { englishTerm: "Dr. Henry Armitage", revisedCoreSet: "Генрі Армітедж", previousEditions: "\"Генрі\n Ермітедж\"" },
    { englishTerm: "Herman Collins", revisedCoreSet: "Герман Коллінс", previousEditions: "Герман Коллінз" },
    { englishTerm: "Daisy Walker", revisedCoreSet: "Дейзі Вокер", previousEditions: "Дейзі Уокер" },
    { englishTerm: "Dr. Milan Christopher", revisedCoreSet: "Доктор Мілан Крістофер", previousEditions: "Доктор Мілан Крістофер" },
    { englishTerm: "Doctor Mortimore", revisedCoreSet: "доктор Мортімер", previousEditions: "доктор Мортімер" },
    { englishTerm: "Lita Chantler", revisedCoreSet: "Літа Чантлер", previousEditions: "Літа Чентлер" },
    { englishTerm: "Nurse Sharon", revisedCoreSet: "медсестра Шерон", previousEditions: "медсестра Шерон" },
    { englishTerm: "Peter Warren", revisedCoreSet: "Пітер Воррен", previousEditions: "Пітер Уоррен" },
    { englishTerm: "Roland Banks", revisedCoreSet: "Роланд Бенкс", previousEditions: "Роланд Бенкс" },
    { englishTerm: "Ruth Turner", revisedCoreSet: "Рут Тернер", previousEditions: "Рут Тернер" },
    { englishTerm: "Fight", revisedCoreSet: "Атака", previousEditions: "Атака" },
    { englishTerm: "Resign", revisedCoreSet: "Відступ", previousEditions: "Відступ" },
    { englishTerm: "Evade", revisedCoreSet: "Втеча", previousEditions: "Втеча" },
    { englishTerm: "Investigate", revisedCoreSet: "Дослідження", previousEditions: "Дослідження" },
    { englishTerm: "Prey", revisedCoreSet: "Жертва", previousEditions: "Жертва" },
    { englishTerm: "Objective", revisedCoreSet: "Мета", previousEditions: "Ціль" },
    { englishTerm: "Permanent", revisedCoreSet: "Незмінна", previousEditions: "n/a" },
    { englishTerm: "Parley", revisedCoreSet: "Перемовини", previousEditions: "Перемовини" },
    { englishTerm: "Victory 1", revisedCoreSet: "Перемога 1", previousEditions: "Перемога 1" },
    { englishTerm: "Spawn", revisedCoreSet: "Поява", previousEditions: "Розміщення" },
    { englishTerm: "Forced", revisedCoreSet: "Примусово", previousEditions: "Примусово" },
    { englishTerm: "Revelation", revisedCoreSet: "Розкриття", previousEditions: "Розкриття" },
    { englishTerm: "Agency", revisedCoreSet: "Агентство", previousEditions: "Агентство" },
    { englishTerm: "Byakhee", revisedCoreSet: "Б’якгі", previousEditions: "Б’якхі" },
    { englishTerm: "Blessed", revisedCoreSet: "Благословення", previousEditions: "n/a" },
    { englishTerm: "Melee", revisedCoreSet: "Ближній бій", previousEditions: "Ближній бій" },
    { englishTerm: "Madness", revisedCoreSet: "Божевілля", previousEditions: "Божевілля" },
    { englishTerm: "Talent", revisedCoreSet: "Вміння", previousEditions: "Талант" },
    { englishTerm: "Firearm", revisedCoreSet: "Вогнепальний", previousEditions: "Вогнепальна" },
    { englishTerm: "Practiced", revisedCoreSet: "Вправність", previousEditions: "Натреноване" },
    { englishTerm: "Innate", revisedCoreSet: "Вроджена", previousEditions: "Вроджене " },
    { englishTerm: "Deep One", revisedCoreSet: "Глибоководний", previousEditions: "Глибоководний" },
    { englishTerm: "Ghoul", revisedCoreSet: "Гуль", previousEditions: "Гуль" },
    { englishTerm: "Humanoid", revisedCoreSet: "Гуманоїд", previousEditions: "Гуманоїд" },
    { englishTerm: "Detective", revisedCoreSet: "Детектив", previousEditions: "Детектив" },
    { englishTerm: "Spirit", revisedCoreSet: "Дух", previousEditions: "Дух" },
    { englishTerm: "Elite", revisedCoreSet: "Елітний", previousEditions: "Елітний" },
    { englishTerm: "Task", revisedCoreSet: "Завдання", previousEditions: "Обов’язок" },
    { englishTerm: "Spell", revisedCoreSet: "Закляття", previousEditions: "Заклинання" },
    { englishTerm: "Supply", revisedCoreSet: "Запас", previousEditions: "Запас" },
    { englishTerm: "Weapon", revisedCoreSet: "Зброя", previousEditions: "Зброя" },
    { englishTerm: "Criminal", revisedCoreSet: "Злочинець", previousEditions: "Злочинець" },
    { englishTerm: "Tool", revisedCoreSet: "Інструмент", previousEditions: "Інструмент" },
    { englishTerm: "Insight", revisedCoreSet: "Інтуїція", previousEditions: "Інтуїція" },
    { englishTerm: "Yithian", revisedCoreSet: "Йітіанець", previousEditions: "Йітіанин" },
    { englishTerm: "Cultist", revisedCoreSet: "Культист", previousEditions: "Культист" },
    { englishTerm: "Hazard", revisedCoreSet: "Лихо", previousEditions: "Ризик" },
    { englishTerm: "Woods", revisedCoreSet: "Ліси", previousEditions: "Ліси" },
    { englishTerm: "Miskatonic", revisedCoreSet: "Міскатонік", previousEditions: "Міскатонік" },
    { englishTerm: "Monster", revisedCoreSet: "Монстр", previousEditions: "Монстр" },
    { englishTerm: "Science", revisedCoreSet: "Наука", previousEditions: "Наука" },
    { englishTerm: "non-Elite", revisedCoreSet: "неелітні ", previousEditions: "не Елітні " },
    { englishTerm: "Illicit", revisedCoreSet: "Незаконний", previousEditions: "Незаконний" },
    { englishTerm: "Nightgaunt", revisedCoreSet: "Нічвида", previousEditions: "Нічна примара" },
    { englishTerm: "Charm", revisedCoreSet: "Оберіг", previousEditions: "Оберіг" },
    { englishTerm: "Pact", revisedCoreSet: "Пакт", previousEditions: "Угода" },
    { englishTerm: "Omen", revisedCoreSet: "Передвістя", previousEditions: "Знамення" },
    { englishTerm: "Obstacle", revisedCoreSet: "Перешкода", previousEditions: "Перешкода" },
    { englishTerm: "Cave", revisedCoreSet: "Печера", previousEditions: "Печера" },
    { englishTerm: "Police", revisedCoreSet: "Поліція", previousEditions: "Поліція" },
    { englishTerm: "Ancient One", revisedCoreSet: "Прадавній", previousEditions: "Прадавній" },
    { englishTerm: "Item", revisedCoreSet: "Предмет", previousEditions: "Предмет" },
    { englishTerm: "Curse", revisedCoreSet: "Прокляття", previousEditions: "Прокляття" },
    { englishTerm: "Relic", revisedCoreSet: "Реліквія", previousEditions: "Реліквія" },
    { englishTerm: "Traits", revisedCoreSet: "Риса", previousEditions: "Риса" },
    { englishTerm: "Ally", revisedCoreSet: "Союзник", previousEditions: "Союзник" },
    { englishTerm: "Silver Twilight", revisedCoreSet: "Срібні сутінки", previousEditions: "Срібні сутінки" },
    { englishTerm: "Creature", revisedCoreSet: "Створіння", previousEditions: "Істота" },
    { englishTerm: "Tactic", revisedCoreSet: "Тактика", previousEditions: "Тактика" },
    { englishTerm: "Dark Young", revisedCoreSet: "Темний нащадок", previousEditions: "Темна Памолодь" },
    { englishTerm: "Terror", revisedCoreSet: "Терор", previousEditions: "Жахіття" },
    { englishTerm: "Tome", revisedCoreSet: "Том", previousEditions: "Книга" },
    { englishTerm: "Armor", revisedCoreSet: "Убрання", previousEditions: "Захист" },
    { englishTerm: "Fortune", revisedCoreSet: "Удача", previousEditions: "Фортуна" },
    { englishTerm: "Central", revisedCoreSet: "Центр", previousEditions: "Центр" },
    { englishTerm: "Sorcerer", revisedCoreSet: "Чаклун", previousEditions: "Чаклун" },
    { englishTerm: "Hex", revisedCoreSet: "Чари", previousEditions: "Чаклунство" },
];

export default data;